# create table category (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=InnoDB;
# create table ingredient (amount decimal(38,2), id bigint not null auto_increment, recipe_id bigint, uom_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
# create table notes (id bigint not null auto_increment, recipe_id bigint, recipe_notes tinytext, primary key (id)) engine=InnoDB;
# create table recipe (cook_time integer, prep_time integer, servings integer, id bigint not null auto_increment, notes_id bigint, description varchar(255), difficulty enum ('EASY','HARD','MODERATE'), source varchar(255), directions tinytext, image tinyblob, url tinytext, primary key (id)) engine=InnoDB;
# create table recipe_category (category_id bigint not null, recipe_id bigint not null, primary key (category_id, recipe_id)) engine=InnoDB;
# create table unit_of_measure (id bigint not null auto_increment, ingredient_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
# alter table notes add constraint UK_gyihyf17jnihru8eoym1tmucb unique (recipe_id);
# alter table recipe add constraint UK_61xwuqykaisawug77hnwnhg3i unique (notes_id);
# alter table unit_of_measure add constraint UK_9yk66e4tvogjjh322wf5wl9pr unique (ingredient_id);
# alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe (id);
# alter table ingredient add constraint FK6iv5l89qmitedn5m2a71kta2t foreign key (uom_id) references unit_of_measure (id);
# alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe (id);
# alter table recipe add constraint FK37al6kcbdasgfnut9xokktie9 foreign key (notes_id) references notes (id);
# alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category (id);
# alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe (id);
# alter table unit_of_measure add constraint FKsuvp4jw48bi3h82hkxrfbgfqu foreign key (ingredient_id) references ingredient (id);
# INSERT INTO category (description) VALUES ('American');
# INSERT INTO category (description) VALUES ('Italian');
# INSERT INTO category (description) VALUES ('Mexican');
# INSERT INTO category (description) VALUES ('Fast Food');
# INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
# INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
# INSERT INTO unit_of_measure (description) VALUES ('Cup');
# INSERT INTO unit_of_measure (description) VALUES ('Pint');
# INSERT INTO unit_of_measure (description) VALUES ('Dash');
# INSERT INTO unit_of_measure (description) VALUES ('Each');
# ALTER TABLE notes DROP COLUMN recipe_notes;
# ALTER TABLE notes ADD recipe_notes TEXT;
# ALTER TABLE recipe MODIFY directions TEXT;
create table category (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (amount decimal(38,2), id bigint not null auto_increment, recipe_id bigint, uom_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table notes (id bigint not null auto_increment, recipe_id bigint, recipe_notes tinytext, primary key (id)) engine=InnoDB;
create table recipe (cook_time integer, prep_time integer, servings integer, id bigint not null auto_increment, notes_id bigint, description varchar(255), difficulty enum ('EASY','HARD','MODERATE'), source varchar(255), directions tinytext, image tinyblob, url tinytext, primary key (id)) engine=InnoDB;
create table recipe_category (category_id bigint not null, recipe_id bigint not null, primary key (category_id, recipe_id)) engine=InnoDB;
create table unit_of_measure (id bigint not null auto_increment, ingredient_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
alter table notes add constraint UK_gyihyf17jnihru8eoym1tmucb unique (recipe_id);
alter table recipe add constraint UK_61xwuqykaisawug77hnwnhg3i unique (notes_id);
alter table unit_of_measure add constraint UK_9yk66e4tvogjjh322wf5wl9pr unique (ingredient_id);
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe (id);
alter table ingredient add constraint FK6iv5l89qmitedn5m2a71kta2t foreign key (uom_id) references unit_of_measure (id);
alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe (id);
alter table recipe add constraint FK37al6kcbdasgfnut9xokktie9 foreign key (notes_id) references notes (id);
alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category (id);
alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe (id);
alter table unit_of_measure add constraint FKsuvp4jw48bi3h82hkxrfbgfqu foreign key (ingredient_id) references ingredient (id);
INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pint');
INSERT INTO unit_of_measure (description) VALUES ('Dash');
INSERT INTO unit_of_measure (description) VALUES ('Each');
create table category (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (amount decimal(38,2), id bigint not null auto_increment, recipe_id bigint, uom_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table notes (id bigint not null auto_increment, recipe_id bigint, recipe_notes tinytext, primary key (id)) engine=InnoDB;
create table recipe (cook_time integer, prep_time integer, servings integer, id bigint not null auto_increment, notes_id bigint, description varchar(255), difficulty enum ('EASY','HARD','MODERATE'), source varchar(255), directions tinytext, image tinyblob, url tinytext, primary key (id)) engine=InnoDB;
create table recipe_category (category_id bigint not null, recipe_id bigint not null, primary key (category_id, recipe_id)) engine=InnoDB;
create table unit_of_measure (id bigint not null auto_increment, ingredient_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
alter table notes add constraint UK_gyihyf17jnihru8eoym1tmucb unique (recipe_id);
alter table recipe add constraint UK_61xwuqykaisawug77hnwnhg3i unique (notes_id);
alter table unit_of_measure add constraint UK_9yk66e4tvogjjh322wf5wl9pr unique (ingredient_id);
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe (id);
alter table ingredient add constraint FK6iv5l89qmitedn5m2a71kta2t foreign key (uom_id) references unit_of_measure (id);
alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe (id);
alter table recipe add constraint FK37al6kcbdasgfnut9xokktie9 foreign key (notes_id) references notes (id);
alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category (id);
alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe (id);
alter table unit_of_measure add constraint FKsuvp4jw48bi3h82hkxrfbgfqu foreign key (ingredient_id) references ingredient (id);
INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pint');
INSERT INTO unit_of_measure (description) VALUES ('Dash');
INSERT INTO unit_of_measure (description) VALUES ('Each');
create table category (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (amount decimal(38,2), id bigint not null auto_increment, recipe_id bigint, uom_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table notes (id bigint not null auto_increment, recipe_id bigint, recipe_notes tinytext, primary key (id)) engine=InnoDB;
create table recipe (cook_time integer, prep_time integer, servings integer, id bigint not null auto_increment, notes_id bigint, description varchar(255), difficulty enum ('EASY','HARD','MODERATE'), source varchar(255), directions tinytext, image tinyblob, url tinytext, primary key (id)) engine=InnoDB;
create table recipe_category (category_id bigint not null, recipe_id bigint not null, primary key (category_id, recipe_id)) engine=InnoDB;
create table unit_of_measure (id bigint not null auto_increment, ingredient_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
alter table notes add constraint UK_gyihyf17jnihru8eoym1tmucb unique (recipe_id);
alter table recipe add constraint UK_61xwuqykaisawug77hnwnhg3i unique (notes_id);
alter table unit_of_measure add constraint UK_9yk66e4tvogjjh322wf5wl9pr unique (ingredient_id);
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe (id);
alter table ingredient add constraint FK6iv5l89qmitedn5m2a71kta2t foreign key (uom_id) references unit_of_measure (id);
alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe (id);
alter table recipe add constraint FK37al6kcbdasgfnut9xokktie9 foreign key (notes_id) references notes (id);
alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category (id);
alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe (id);
alter table unit_of_measure add constraint FKsuvp4jw48bi3h82hkxrfbgfqu foreign key (ingredient_id) references ingredient (id);
INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pint');
INSERT INTO unit_of_measure (description) VALUES ('Dash');
INSERT INTO unit_of_measure (description) VALUES ('Each');
create table category (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (amount decimal(38,2), id bigint not null auto_increment, recipe_id bigint, uom_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table notes (id bigint not null auto_increment, recipe_id bigint, recipe_notes tinytext, primary key (id)) engine=InnoDB;
create table recipe (cook_time integer, prep_time integer, servings integer, id bigint not null auto_increment, notes_id bigint, description varchar(255), difficulty enum ('EASY','HARD','MODERATE'), source varchar(255), directions tinytext, image tinyblob, url tinytext, primary key (id)) engine=InnoDB;
create table recipe_category (category_id bigint not null, recipe_id bigint not null, primary key (category_id, recipe_id)) engine=InnoDB;
create table unit_of_measure (id bigint not null auto_increment, ingredient_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
alter table notes add constraint UK_gyihyf17jnihru8eoym1tmucb unique (recipe_id);
alter table recipe add constraint UK_61xwuqykaisawug77hnwnhg3i unique (notes_id);
alter table unit_of_measure add constraint UK_9yk66e4tvogjjh322wf5wl9pr unique (ingredient_id);
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe (id);
alter table ingredient add constraint FK6iv5l89qmitedn5m2a71kta2t foreign key (uom_id) references unit_of_measure (id);
alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe (id);
alter table recipe add constraint FK37al6kcbdasgfnut9xokktie9 foreign key (notes_id) references notes (id);
alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category (id);
alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe (id);
alter table unit_of_measure add constraint FKsuvp4jw48bi3h82hkxrfbgfqu foreign key (ingredient_id) references ingredient (id);
create table category (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (amount decimal(38,2), id bigint not null auto_increment, recipe_id bigint, uom_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table notes (id bigint not null auto_increment, recipe_id bigint, recipe_notes tinytext, primary key (id)) engine=InnoDB;
create table recipe (cook_time integer, prep_time integer, servings integer, id bigint not null auto_increment, notes_id bigint, description varchar(255), difficulty enum ('EASY','HARD','MODERATE'), source varchar(255), directions tinytext, image tinyblob, url tinytext, primary key (id)) engine=InnoDB;
create table recipe_category (category_id bigint not null, recipe_id bigint not null, primary key (category_id, recipe_id)) engine=InnoDB;
create table unit_of_measure (id bigint not null auto_increment, ingredient_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
alter table notes add constraint UK_gyihyf17jnihru8eoym1tmucb unique (recipe_id);
alter table recipe add constraint UK_61xwuqykaisawug77hnwnhg3i unique (notes_id);
alter table unit_of_measure add constraint UK_9yk66e4tvogjjh322wf5wl9pr unique (ingredient_id);
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe (id);
alter table ingredient add constraint FK6iv5l89qmitedn5m2a71kta2t foreign key (uom_id) references unit_of_measure (id);
alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe (id);
alter table recipe add constraint FK37al6kcbdasgfnut9xokktie9 foreign key (notes_id) references notes (id);
alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category (id);
alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe (id);
alter table unit_of_measure add constraint FKsuvp4jw48bi3h82hkxrfbgfqu foreign key (ingredient_id) references ingredient (id);
create table category (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (amount decimal(38,2), id bigint not null auto_increment, recipe_id bigint, uom_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table notes (id bigint not null auto_increment, recipe_id bigint, recipe_notes tinytext, primary key (id)) engine=InnoDB;
create table recipe (cook_time integer, prep_time integer, servings integer, id bigint not null auto_increment, notes_id bigint, description varchar(255), difficulty enum ('EASY','HARD','MODERATE'), source varchar(255), directions tinytext, image tinyblob, url tinytext, primary key (id)) engine=InnoDB;
create table recipe_category (category_id bigint not null, recipe_id bigint not null, primary key (category_id, recipe_id)) engine=InnoDB;
create table unit_of_measure (id bigint not null auto_increment, ingredient_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
alter table notes add constraint UK_gyihyf17jnihru8eoym1tmucb unique (recipe_id);
alter table recipe add constraint UK_61xwuqykaisawug77hnwnhg3i unique (notes_id);
alter table unit_of_measure add constraint UK_9yk66e4tvogjjh322wf5wl9pr unique (ingredient_id);
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe (id);
alter table ingredient add constraint FK6iv5l89qmitedn5m2a71kta2t foreign key (uom_id) references unit_of_measure (id);
alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe (id);
alter table recipe add constraint FK37al6kcbdasgfnut9xokktie9 foreign key (notes_id) references notes (id);
alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category (id);
alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe (id);
alter table unit_of_measure add constraint FKsuvp4jw48bi3h82hkxrfbgfqu foreign key (ingredient_id) references ingredient (id);
create table category (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (amount decimal(38,2), id bigint not null auto_increment, recipe_id bigint, uom_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table notes (id bigint not null auto_increment, recipe_id bigint, recipe_notes tinytext, primary key (id)) engine=InnoDB;
create table recipe (cook_time integer, prep_time integer, servings integer, id bigint not null auto_increment, notes_id bigint, description varchar(255), difficulty enum ('EASY','HARD','MODERATE'), source varchar(255), directions tinytext, image tinyblob, url tinytext, primary key (id)) engine=InnoDB;
create table recipe_category (category_id bigint not null, recipe_id bigint not null, primary key (category_id, recipe_id)) engine=InnoDB;
create table unit_of_measure (id bigint not null auto_increment, ingredient_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
alter table notes add constraint UK_gyihyf17jnihru8eoym1tmucb unique (recipe_id);
alter table recipe add constraint UK_61xwuqykaisawug77hnwnhg3i unique (notes_id);
alter table unit_of_measure add constraint UK_9yk66e4tvogjjh322wf5wl9pr unique (ingredient_id);
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe (id);
alter table ingredient add constraint FK6iv5l89qmitedn5m2a71kta2t foreign key (uom_id) references unit_of_measure (id);
alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe (id);
alter table recipe add constraint FK37al6kcbdasgfnut9xokktie9 foreign key (notes_id) references notes (id);
alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category (id);
alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe (id);
alter table unit_of_measure add constraint FKsuvp4jw48bi3h82hkxrfbgfqu foreign key (ingredient_id) references ingredient (id);
INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pint');
INSERT INTO unit_of_measure (description) VALUES ('Dash');
INSERT INTO unit_of_measure (description) VALUES ('Each');
create table category (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (amount decimal(38,2), id bigint not null auto_increment, recipe_id bigint, uom_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table notes (id bigint not null auto_increment, recipe_id bigint, recipe_notes tinytext, primary key (id)) engine=InnoDB;
create table recipe (cook_time integer, prep_time integer, servings integer, id bigint not null auto_increment, notes_id bigint, description varchar(255), difficulty enum ('EASY','HARD','MODERATE'), source varchar(255), directions tinytext, image tinyblob, url tinytext, primary key (id)) engine=InnoDB;
create table recipe_category (category_id bigint not null, recipe_id bigint not null, primary key (category_id, recipe_id)) engine=InnoDB;
create table unit_of_measure (id bigint not null auto_increment, ingredient_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
alter table notes add constraint UK_gyihyf17jnihru8eoym1tmucb unique (recipe_id);
alter table recipe add constraint UK_61xwuqykaisawug77hnwnhg3i unique (notes_id);
alter table unit_of_measure add constraint UK_9yk66e4tvogjjh322wf5wl9pr unique (ingredient_id);
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe (id);
alter table ingredient add constraint FK6iv5l89qmitedn5m2a71kta2t foreign key (uom_id) references unit_of_measure (id);
alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe (id);
alter table recipe add constraint FK37al6kcbdasgfnut9xokktie9 foreign key (notes_id) references notes (id);
alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category (id);
alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe (id);
alter table unit_of_measure add constraint FKsuvp4jw48bi3h82hkxrfbgfqu foreign key (ingredient_id) references ingredient (id);
INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pint');
INSERT INTO unit_of_measure (description) VALUES ('Dash');
INSERT INTO unit_of_measure (description) VALUES ('Each');
create table category (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (amount decimal(38,2), id bigint not null auto_increment, recipe_id bigint, uom_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table notes (id bigint not null auto_increment, recipe_id bigint, recipe_notes tinytext, primary key (id)) engine=InnoDB;
create table recipe (cook_time integer, prep_time integer, servings integer, id bigint not null auto_increment, notes_id bigint, description varchar(255), difficulty enum ('EASY','HARD','MODERATE'), source varchar(255), directions tinytext, image tinyblob, url tinytext, primary key (id)) engine=InnoDB;
create table recipe_category (category_id bigint not null, recipe_id bigint not null, primary key (category_id, recipe_id)) engine=InnoDB;
create table unit_of_measure (id bigint not null auto_increment, ingredient_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
alter table notes add constraint UK_gyihyf17jnihru8eoym1tmucb unique (recipe_id);
alter table recipe add constraint UK_61xwuqykaisawug77hnwnhg3i unique (notes_id);
alter table unit_of_measure add constraint UK_9yk66e4tvogjjh322wf5wl9pr unique (ingredient_id);
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe (id);
alter table ingredient add constraint FK6iv5l89qmitedn5m2a71kta2t foreign key (uom_id) references unit_of_measure (id);
alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe (id);
alter table recipe add constraint FK37al6kcbdasgfnut9xokktie9 foreign key (notes_id) references notes (id);
alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category (id);
alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe (id);
alter table unit_of_measure add constraint FKsuvp4jw48bi3h82hkxrfbgfqu foreign key (ingredient_id) references ingredient (id);
INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pint');
INSERT INTO unit_of_measure (description) VALUES ('Dash');
INSERT INTO unit_of_measure (description) VALUES ('Each');
create table category (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (amount decimal(38,2), id bigint not null auto_increment, recipe_id bigint, uom_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table notes (id bigint not null auto_increment, recipe_id bigint, recipe_notes tinytext, primary key (id)) engine=InnoDB;
create table recipe (cook_time integer, prep_time integer, servings integer, id bigint not null auto_increment, notes_id bigint, description varchar(255), difficulty enum ('EASY','HARD','MODERATE'), source varchar(255), directions tinytext, image tinyblob, url tinytext, primary key (id)) engine=InnoDB;
create table recipe_category (category_id bigint not null, recipe_id bigint not null, primary key (category_id, recipe_id)) engine=InnoDB;
create table unit_of_measure (id bigint not null auto_increment, ingredient_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
alter table notes add constraint UK_gyihyf17jnihru8eoym1tmucb unique (recipe_id);
alter table recipe add constraint UK_61xwuqykaisawug77hnwnhg3i unique (notes_id);
alter table unit_of_measure add constraint UK_9yk66e4tvogjjh322wf5wl9pr unique (ingredient_id);
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe (id);
alter table ingredient add constraint FK6iv5l89qmitedn5m2a71kta2t foreign key (uom_id) references unit_of_measure (id);
alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe (id);
alter table recipe add constraint FK37al6kcbdasgfnut9xokktie9 foreign key (notes_id) references notes (id);
alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category (id);
alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe (id);
alter table unit_of_measure add constraint FKsuvp4jw48bi3h82hkxrfbgfqu foreign key (ingredient_id) references ingredient (id);
INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pint');
INSERT INTO unit_of_measure (description) VALUES ('Dash');
INSERT INTO unit_of_measure (description) VALUES ('Each');
create table category (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (amount decimal(38,2), id bigint not null auto_increment, recipe_id bigint, uom_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table notes (id bigint not null auto_increment, recipe_id bigint, recipe_notes tinytext, primary key (id)) engine=InnoDB;
create table recipe (cook_time integer, prep_time integer, servings integer, id bigint not null auto_increment, notes_id bigint, description varchar(255), difficulty enum ('EASY','HARD','MODERATE'), source varchar(255), directions tinytext, image tinyblob, url tinytext, primary key (id)) engine=InnoDB;
create table recipe_category (category_id bigint not null, recipe_id bigint not null, primary key (category_id, recipe_id)) engine=InnoDB;
create table unit_of_measure (id bigint not null auto_increment, ingredient_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
alter table notes add constraint UK_gyihyf17jnihru8eoym1tmucb unique (recipe_id);
alter table recipe add constraint UK_61xwuqykaisawug77hnwnhg3i unique (notes_id);
alter table unit_of_measure add constraint UK_9yk66e4tvogjjh322wf5wl9pr unique (ingredient_id);
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe (id);
alter table ingredient add constraint FK6iv5l89qmitedn5m2a71kta2t foreign key (uom_id) references unit_of_measure (id);
alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe (id);
alter table recipe add constraint FK37al6kcbdasgfnut9xokktie9 foreign key (notes_id) references notes (id);
alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category (id);
alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe (id);
alter table unit_of_measure add constraint FKsuvp4jw48bi3h82hkxrfbgfqu foreign key (ingredient_id) references ingredient (id);
INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pint');
INSERT INTO unit_of_measure (description) VALUES ('Dash');
INSERT INTO unit_of_measure (description) VALUES ('Each');
create table category (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (amount decimal(38,2), id bigint not null auto_increment, recipe_id bigint, uom_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table notes (id bigint not null auto_increment, recipe_id bigint, recipe_notes tinytext, primary key (id)) engine=InnoDB;
create table recipe (cook_time integer, prep_time integer, servings integer, id bigint not null auto_increment, notes_id bigint, description varchar(255), difficulty enum ('EASY','HARD','MODERATE'), source varchar(255), directions tinytext, image tinyblob, url tinytext, primary key (id)) engine=InnoDB;
create table recipe_category (category_id bigint not null, recipe_id bigint not null, primary key (category_id, recipe_id)) engine=InnoDB;
create table unit_of_measure (id bigint not null auto_increment, ingredient_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
alter table notes add constraint UK_gyihyf17jnihru8eoym1tmucb unique (recipe_id);
alter table recipe add constraint UK_61xwuqykaisawug77hnwnhg3i unique (notes_id);
alter table unit_of_measure add constraint UK_9yk66e4tvogjjh322wf5wl9pr unique (ingredient_id);
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe (id);
alter table ingredient add constraint FK6iv5l89qmitedn5m2a71kta2t foreign key (uom_id) references unit_of_measure (id);
alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe (id);
alter table recipe add constraint FK37al6kcbdasgfnut9xokktie9 foreign key (notes_id) references notes (id);
alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category (id);
alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe (id);
alter table unit_of_measure add constraint FKsuvp4jw48bi3h82hkxrfbgfqu foreign key (ingredient_id) references ingredient (id);
INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pint');
INSERT INTO unit_of_measure (description) VALUES ('Dash');
INSERT INTO unit_of_measure (description) VALUES ('Each');
create table category (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (amount decimal(38,2), id bigint not null auto_increment, recipe_id bigint, uom_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
create table notes (id bigint not null auto_increment, recipe_id bigint, recipe_notes tinytext, primary key (id)) engine=InnoDB;
create table recipe (cook_time integer, prep_time integer, servings integer, id bigint not null auto_increment, notes_id bigint, description varchar(255), difficulty enum ('EASY','HARD','MODERATE'), source varchar(255), directions tinytext, image tinyblob, url tinytext, primary key (id)) engine=InnoDB;
create table recipe_category (category_id bigint not null, recipe_id bigint not null, primary key (category_id, recipe_id)) engine=InnoDB;
create table unit_of_measure (id bigint not null auto_increment, ingredient_id bigint, description varchar(255), primary key (id)) engine=InnoDB;
alter table notes add constraint UK_gyihyf17jnihru8eoym1tmucb unique (recipe_id);
alter table recipe add constraint UK_61xwuqykaisawug77hnwnhg3i unique (notes_id);
alter table unit_of_measure add constraint UK_9yk66e4tvogjjh322wf5wl9pr unique (ingredient_id);
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe (id);
alter table ingredient add constraint FK6iv5l89qmitedn5m2a71kta2t foreign key (uom_id) references unit_of_measure (id);
alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe (id);
alter table recipe add constraint FK37al6kcbdasgfnut9xokktie9 foreign key (notes_id) references notes (id);
alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category (id);
alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe (id);
alter table unit_of_measure add constraint FKsuvp4jw48bi3h82hkxrfbgfqu foreign key (ingredient_id) references ingredient (id);
INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pint');
INSERT INTO unit_of_measure (description) VALUES ('Dash');
INSERT INTO unit_of_measure (description) VALUES ('Each');
